###**10 September**

**Cara membuat array**

In [ ]:
import numpy as np


In [ ]:
# Menggunakan np.array

array1= np.array([1,2,3,4,10])
array1

array([ 1,  2,  3,  4, 10])

In [ ]:
# Menggunakan zeros() => array berisi bilangan nol

array2=np.zeros(10)
array2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Menggunakan ones() => array berisi angka 1 semua

array3 = np.ones(10)
array3

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Menggunakan np.empty() => membuat array dengan isi yg random tergantung dari memori

array4= np.empty(5)
array4

array([0.0e+000, 2.5e-323, 2.5e-323, 2.5e-323, 2.5e-323])

In [ ]:
# Menggunakan np.arange() => membuat array dengan range tertentu

array5= np.arange(1,15,3)   # arange(start, stop, step)
array5

array([ 1,  4,  7, 10, 13])

In [ ]:
# Menggunakan np.random.random()

**Penggunaan Add, Remove, and Sort**

In [ ]:
# Penggunaan np.append() untuk menambah item pada array
array5= np.arange(1,15,3)

array5= np.append(array5, [1,10])
array5


array([ 1,  4,  7, 10, 13,  1, 10])

In [ ]:
# Penggunaan np.delete() untuk menghapus item pada array
array5= np.arange(1,15,3)
array5= np.delete(array5,[-1])

array5

array([ 1,  4,  7, 10])

In [ ]:
# Penggunaan sort() untuk mengurutkan item dari nilai terkecil
array5= np.array([1,20,3,4,1,5,36,7,4,31])

array5=np.sort(array5)
array5


array([ 1,  1,  3,  4,  4,  5,  7, 20, 31, 36])

**Shape dan Size Array**

In [ ]:
# Penggunaan .ndim, .size, dan .shape

array5= np.array([1,20,3,4,1,5,36,7,4,31])
array5.ndim  # Untuk melihat dimensi array

array5.size  # Untuk melihat jumlah item pada array

array5.shape # Untuk melihat kolom x baris array

(10,)

**Reshape dan Resize**

In [ ]:
# Penggunaan reshape() untuk mengubah array ke dalam dimensi baru tanpa mengubah datanya
array5= np.array([1,20,3,4,1,5,36,7,4,31])

array5=array5.reshape(2,5)
array5

array([[ 1, 20,  3,  4,  1],
       [ 5, 36,  7,  4, 31]])

In [ ]:
# Penggunaan resize() untuk mengubah ukuran array baik dengan menghapus atau menamabh suatu elemen atau tidak sama seklali
array5= np.array([1,20,3,4,1,5,36,7,4,31])

array5=array5.resize(2,5)

**Penggunaan Newaxis Array 1D ke 2D, dts**

In [ ]:
array1= np.array([1,20,3,4,1,5,36,7,4,31])

array2=array1[np.newaxis]
np.shape(array2)

(1, 10)

**Indexing dan Slicing**

In [ ]:
# Sederhana
array1= np.array([1,20,3,4,1,5,36,7,4,31])

array1[1:5]


array([20,  3,  4,  1])

In [ ]:
# Advanced

array1= np.array([1,20,3,4,1,5,36,7,4,31])

array1[array1<10]   # Bisa digunakan pada kondisi lainnya

array([1, 3, 4, 1, 5, 7, 4])

**Creating array from Existing Data**

In [ ]:
# Menggunakan slicing
array1= np.array([1,20,3,4,1,5,36,7,4,31])

array2 = array1[array1<10]   # Bisa digunakan pada kondisi lainnya

array2

array([1, 3, 4, 1, 5, 7, 4])

Penggunaan vstack() dan hstack()

In [ ]:
# Menggunakan vstack() untuk menumpuk secara vertikal
array1= np.array([1,20,3,4,1,5,36,7,4,31])
array2= np.arange(1,11)

array3= np.vstack((array1,array2))
array3

array([[ 1, 20,  3,  4,  1,  5, 36,  7,  4, 31],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [ ]:
# Menggunakan hstack() untuk menumpuk secara horizontal
array1= np.array([1,20,3,4,1,5,36,7,4,31])
array2= np.arange(1,11)

array3= np.hstack((array1,array2))
array3

array([ 1, 20,  3,  4,  1,  5, 36,  7,  4, 31,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10])

Penggunaan hsplit dan vsplit

In [ ]:
array1= np.array([1,20,3,4,1,5,36,7,4,31])
array2= np.arange(1,11)

array3= np.vstack((array1,array2))


# Kemudian displit

np.vsplit(array3,2)

[array([[ 1, 20,  3,  4,  1,  5, 36,  7,  4, 31]]),
 array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])]

In [ ]:
# Menggunakan hstack() untuk menumpuk secara horizontal
array1= np.array([1,20,3,4,1,5,36,7,4,31])
array2= np.arange(1,11)

array3= np.hstack((array1,array2))

# Kemudian displit

np.hsplit(array3,4)

[array([ 1, 20,  3,  4,  1]),
 array([ 5, 36,  7,  4, 31]),
 array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10])]

Menggunakan copy() atau view()

**Basic Operation di Array**

Penggunaan array memungkinkan terjadinya operasi matematika baik itu pengurangan, penjumlaha, perkalian ataupun pembagian dengan array lain atau dengan bilangan skalar.

In [ ]:
array1= np.array([[1,2,3],
                   [2,3,4],
                   [8,6,4]])
# Menggunakan function sum()

array2= array1.sum(axis=1)
array2

array([ 6,  9, 18])

**Beberapa Function lainnya**

1. Function .max()
2. Function .min()
3. Function .sum()

In [ ]:
np.random.random((2,5))

array([[0.0025778 , 0.43462916, 0.17732504, 0.02086259, 0.45188607],
       [0.28693504, 0.28495896, 0.01046639, 0.74895309, 0.24530487]])

**Function Transpose**

In [ ]:
data= np.array([[1,2,3],[4,5,6]])

d

array([[1, 4],
       [2, 5],
       [3, 6]])